# Generated by Django 6.0.3 on 2026-03-18 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('definition', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('current_step', models.CharField(max_length=50)),
                ('context', models.JSONField(default=dict)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.workflowdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('response', models.JSONField(default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.workflowinstance')),
            ],
        ),
    ]
